services:
  mariadb:
    image: mariadb:epinaud
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: always
    secrets:
      - mysql_pwd
      - mysql_root_pwd

  wordpress:
    image: wordpress:epinaud
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: always
    secrets:
      - mysql_pwd
      - wp_usr_pwd
      - wp_admin_pwd
  nginx:
    image: nginx:epinaud
    container_name: nginx
    build:
      context: requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
    restart: always

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/epinaud/data/mariadb
      o: bind
  wordpress_data:
     driver: local
     driver_opts:
      type: none
      o: bind
      device: /home/epinaud/data/wordpress

networks:
  inception_network:
    driver: bridge

secrets:
  mysql_pwd:
    file: /home/epinaud/Inception/secrets/mysql_pwd.txt
  mysql_root_pwd:
    file: /home/epinaud/Inception/secrets/mysql_root_pwd.txt
  wp_usr_pwd:
    file: /home/epinaud/Inception/secrets/wp_usr_pwd.txt
  wp_admin_pwd:
    file: /home/epinaud/Inception/secrets/wp_admin_pwd.txt
